/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package figurasgeometricas;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author Andrés Gómez - Ruby Cárdenas
 * @version 1.0.0 Esta clase crea la interfaz que el usuario verá cuando el
 * proyecto se ejecute
 */
public class Interfaz extends javax.swing.JFrame {

    private String coordenada1Px;
    private String coordenada1Py;
    private String coordenada2Px;
    private String coordenada2Py;
    private String coordenada3Px;
    private String coordenada3Py;
    private String coordenada4Px;
    private String coordenada4Py;
    private int color;
    private int seleccionFigura;
    private int opcionColor;
    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        planoCartesiano = new javax.swing.JPanel();
        tituloPrincipal = new javax.swing.JLabel();
        seleccionarFigura = new javax.swing.JComboBox();
        seleccionarColor = new javax.swing.JComboBox();
        digiteCoordenadas = new javax.swing.JLabel();
        tituloCoordenada1 = new javax.swing.JLabel();
        coor1PosicionX = new javax.swing.JTextField();
        coor1PosicionY = new javax.swing.JTextField();
        tituloCoordenada2 = new javax.swing.JLabel();
        coor2PosicionX = new javax.swing.JTextField();
        coor2PosicionY = new javax.swing.JTextField();
        tituloCoordenada3 = new javax.swing.JLabel();
        coor3PosicionX = new javax.swing.JTextField();
        coor3PosicionY = new javax.swing.JTextField();
        tituloCoordenada4 = new javax.swing.JLabel();
        coor4PosicionX = new javax.swing.JTextField();
        coor4PosicionY = new javax.swing.JTextField();
        graficar = new javax.swing.JButton();
        tituloArea = new javax.swing.JLabel();
        tituloPerimetro = new javax.swing.JLabel();
        area = new javax.swing.JLabel();
        perimetro = new javax.swing.JLabel();
        tituloTipoTriangulo = new javax.swing.JLabel();
        tipoTriangulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout planoCartesianoLayout = new javax.swing.GroupLayout(planoCartesiano);
        planoCartesiano.setLayout(planoCartesianoLayout);
        planoCartesianoLayout.setHorizontalGroup(
            planoCartesianoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        planoCartesianoLayout.setVerticalGroup(
            planoCartesianoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tituloPrincipal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloPrincipal.setText("FIGURAS GEOMÉTRICAS");
        tituloPrincipal.setName("tituloGeneral"); // NOI18N

        seleccionarFigura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione la figura", "Triángulo", "Cuadrado", "Rectangulo" }));
        seleccionarFigura.setName("seleccionarFigura"); // NOI18N
        seleccionarFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarFiguraActionPerformed(evt);
            }
        });

        seleccionarColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione el Color", "Azul", "Amarillo", "Rojo", "Verde", "Violeta", "Negro" }));
        seleccionarColor.setName("seleccionarColor"); // NOI18N

        digiteCoordenadas.setText("Digite las coordenadas");
        digiteCoordenadas.setToolTipText("");
        digiteCoordenadas.setName("tituloCoordenadas"); // NOI18N

        tituloCoordenada1.setText("Primera Coordenada (X,Y)");
        tituloCoordenada1.setName("tituloCoor1"); // NOI18N

        coor1PosicionX.setName("coor1PosicionX"); // NOI18N

        coor1PosicionY.setName("coor1PosicionY"); // NOI18N

        tituloCoordenada2.setText("Segunda Coordenada (X,Y)");
        tituloCoordenada2.setName("tituloCoor2"); // NOI18N

        coor2PosicionX.setName("coor1PosicionX"); // NOI18N

        coor2PosicionY.setName("coor2PosicionY"); // NOI18N

        tituloCoordenada3.setText("Tercera Coordenada (X,Y)");
        tituloCoordenada3.setName("tituloCoor3"); // NOI18N

        coor3PosicionX.setName("coor1PosicionX"); // NOI18N

        coor3PosicionY.setName("coor1PosicionY"); // NOI18N

        tituloCoordenada4.setText("Cuarta coordenada (X,Y)");
        tituloCoordenada4.setName("tituloCoor4"); // NOI18N

        coor4PosicionX.setName("coor1PosicionX"); // NOI18N

        coor4PosicionY.setName("coor1PosicionY"); // NOI18N

        graficar.setText("GRAFICAR Y CALCULAR");
        graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficarActionPerformed(evt);
            }
        });

        tituloArea.setText("Area de la figura");

        tituloPerimetro.setText("Perímetro de la figura");

        area.setText("---");

        perimetro.setText("---");

        tituloTipoTriangulo.setText("Tipo de triangulo");

        tipoTriangulo.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(tituloPrincipal)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(planoCartesiano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(coor2PosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(coor2PosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tituloCoordenada1)
                                            .addComponent(tituloCoordenada2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(coor1PosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor1PosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(seleccionarFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tituloCoordenada3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(coor3PosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor3PosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tituloCoordenada4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(coor4PosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(coor4PosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(seleccionarColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(area)
                                    .addComponent(tituloArea)
                                    .addComponent(tituloTipoTriangulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoTriangulo)
                                    .addComponent(tituloPerimetro)
                                    .addComponent(perimetro))
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(graficar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(digiteCoordenadas)
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(tituloPrincipal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(planoCartesiano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seleccionarFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccionarColor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(digiteCoordenadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tituloCoordenada1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tituloCoordenada3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(coor1PosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coor1PosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coor3PosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coor3PosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tituloCoordenada2)
                                    .addComponent(tituloCoordenada4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(coor2PosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coor2PosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coor4PosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coor4PosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(tituloArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tituloPerimetro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(perimetro)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tituloTipoTriangulo)
                                    .addComponent(tipoTriangulo))))))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public class DibujarFiguras extends JPanel {

        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            seleccionarColor();
            switch (opcionColor) {
                case 1: {
                    g.setColor(Color.blue);
                }
                break;
                case 2: {
                    g.setColor(Color.yellow);
                }
                break;
                case 3: {
                    g.setColor(Color.red);
                }
                break;
                case 4: {
                    g.setColor(Color.green);
                }
                break;
                case 5: {
                    g.setColor(Color.black);
                }
                break;
                default: {
                    g.setColor(Color.white);
                }
            }
            

            switch (seleccionFigura) {
                case 1:
                    g.drawLine(Integer.parseInt(coordenada1Px), Integer.parseInt(coordenada1Py), Integer.parseInt(coordenada2Px), Integer.parseInt(coordenada2Py));
                    g.drawLine(Integer.parseInt(coordenada2Px), Integer.parseInt(coordenada2Py), Integer.parseInt(coordenada3Px), Integer.parseInt(coordenada3Py));
                    g.drawLine(Integer.parseInt(coordenada3Px), Integer.parseInt(coordenada3Py), Integer.parseInt(coordenada1Px), Integer.parseInt(coordenada1Py));

                    break;

                case 2:
                    g.drawLine(Integer.parseInt(coordenada1Px), Integer.parseInt(coordenada1Py), Integer.parseInt(coordenada2Px), Integer.parseInt(coordenada2Py));
                    g.drawLine(Integer.parseInt(coordenada2Px), Integer.parseInt(coordenada2Py), Integer.parseInt(coordenada3Px), Integer.parseInt(coordenada3Py));
                    g.drawLine(Integer.parseInt(coordenada3Px), Integer.parseInt(coordenada3Py), Integer.parseInt(coordenada4Px), Integer.parseInt(coordenada4Py));
                    g.drawLine(Integer.parseInt(coordenada4Px), Integer.parseInt(coordenada4Py), Integer.parseInt(coordenada1Px), Integer.parseInt(coordenada1Py));

                    break;

                case 3:
                    g.drawLine(Integer.parseInt(coordenada1Px), Integer.parseInt(coordenada1Py), Integer.parseInt(coordenada2Px), Integer.parseInt(coordenada2Py));
                    g.drawLine(Integer.parseInt(coordenada2Px), Integer.parseInt(coordenada2Py), Integer.parseInt(coordenada3Px), Integer.parseInt(coordenada3Py));
                    g.drawLine(Integer.parseInt(coordenada3Px), Integer.parseInt(coordenada3Py), Integer.parseInt(coordenada4Px), Integer.parseInt(coordenada4Py));
                    g.drawLine(Integer.parseInt(coordenada4Px), Integer.parseInt(coordenada4Py), Integer.parseInt(coordenada1Px), Integer.parseInt(coordenada1Py));

                    break;
            }
        }
    }

    private void dibujar() {
        Interfaz.DibujarFiguras dibujo = new Interfaz.DibujarFiguras();

        dibujo.setBounds(100, 100, 1000, 1000);
        dibujo.setOpaque(false);
        planoCartesiano.add(dibujo);
        planoCartesiano.repaint();
    }


    private void seleccionarFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarFiguraActionPerformed
        seleccionarFigura();
    }//GEN-LAST:event_seleccionarFiguraActionPerformed

    private void graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficarActionPerformed
        obtenerDatos();
        FigurasGeometricas figuras = new FigurasGeometricas(Integer.parseInt(coordenada1Px), Integer.parseInt(coordenada2Px), Integer.parseInt(coordenada3Px), Integer.parseInt(coordenada1Py), Integer.parseInt(coordenada2Py), Integer.parseInt(coordenada3Py));
        CuadradoRectangulo cr = new CuadradoRectangulo(Integer.parseInt(coordenada1Px), Integer.parseInt(coordenada2Px), Integer.parseInt(coordenada3Px), Integer.parseInt(coordenada4Px), Integer.parseInt(coordenada1Py), Integer.parseInt(coordenada2Py), Integer.parseInt(coordenada3Py), Integer.parseInt(coordenada4Py));
        Triangulo tr = new Triangulo(Integer.parseInt(coordenada1Px), Integer.parseInt(coordenada2Px), Integer.parseInt(coordenada3Px), Integer.parseInt(coordenada1Py), Integer.parseInt(coordenada2Py), Integer.parseInt(coordenada3Py));
        switch (seleccionFigura) {
            case 1:
                figuras.hallarLados(Integer.parseInt(coordenada1Px), Integer.parseInt(coordenada2Px), Integer.parseInt(coordenada3Px), Integer.parseInt(coordenada1Py), Integer.parseInt(coordenada2Py), Integer.parseInt(coordenada3Py));
                figuras.hallarPerimetro();
                figuras.hallarArea();
                figuras.getPerimetro();                
                area.setText(String.valueOf(figuras.getArea()));
                perimetro.setText(String.valueOf(figuras.getPerimetro()));
                
                break;
            case 2:
                
                break;
        }

        seleccionarColor();
        seleccionarFigura();
        dibujar();
    }//GEN-LAST:event_graficarActionPerformed

    public void obtenerDatos() {
        coordenada1Px = coor1PosicionX.getText();
        coordenada1Py = coor1PosicionY.getText();
        coordenada2Px = coor2PosicionX.getText();
        coordenada2Py = coor2PosicionY.getText();
        coordenada3Px = coor3PosicionX.getText();
        coordenada3Py = coor3PosicionY.getText();
        coordenada4Px = coor4PosicionX.getText();
        coordenada4Py = coor4PosicionY.getText();

    }

    public void seleccionarFigura() {
        int opcion = seleccionarFigura.getSelectedIndex();
        seleccionFigura = opcion;
        switch (opcion) {
            case 1: {
                tituloCoordenada4.setVisible(false);
                coor4PosicionX.setVisible(false);
                coor4PosicionY.setVisible(false);
            }
            break;
            default: {
                tituloCoordenada4.setVisible(true);
                coor4PosicionX.setVisible(true);
                coor4PosicionY.setVisible(true);
            }
        }
    }

    public void seleccionarColor() {
        opcionColor = seleccionarColor.getSelectedIndex();        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel area;
    private javax.swing.JTextField coor1PosicionX;
    private javax.swing.JTextField coor1PosicionY;
    private javax.swing.JTextField coor2PosicionX;
    private javax.swing.JTextField coor2PosicionY;
    private javax.swing.JTextField coor3PosicionX;
    private javax.swing.JTextField coor3PosicionY;
    private javax.swing.JTextField coor4PosicionX;
    private javax.swing.JTextField coor4PosicionY;
    private javax.swing.JLabel digiteCoordenadas;
    private javax.swing.JButton graficar;
    private javax.swing.JLabel perimetro;
    private javax.swing.JPanel planoCartesiano;
    private javax.swing.JComboBox seleccionarColor;
    private javax.swing.JComboBox seleccionarFigura;
    private javax.swing.JLabel tipoTriangulo;
    private javax.swing.JLabel tituloArea;
    private javax.swing.JLabel tituloCoordenada1;
    private javax.swing.JLabel tituloCoordenada2;
    private javax.swing.JLabel tituloCoordenada3;
    private javax.swing.JLabel tituloCoordenada4;
    private javax.swing.JLabel tituloPerimetro;
    private javax.swing.JLabel tituloPrincipal;
    private javax.swing.JLabel tituloTipoTriangulo;
    // End of variables declaration//GEN-END:variables
}
